name: rainride
description: A simple weather-aware commute app for motorcyclists.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.6
  flutter_typeahead: ^4.0.0
  flutter_keyboard_visibility:
    path: flutter_keyboard_visibility
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.2.2

dependency_overrides:
  flutter_keyboard_visibility:
    path: flutter_keyboard_visibility



dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

